#!/usr/bin/env python3
"""Replace the COURSES array in sariro-data.ts with 12 new builder-program
courses. Each course has full syllabus (modules + lessons).
- Beginner: $199, 5 modules, 30 lessons (6 per module)
- Intermediate: $299, 7 modules, 42 lessons (6 per module)
- Advanced: $699, 16 modules, 96 lessons (6 per module)
"""
import re
from pathlib import Path

FILE = Path('/home/z/my-project/src/lib/sariro-data.ts')
src = FILE.read_text()

# The new COURSES array — 12 courses with full syllabi
NEW_COURSES = '''export const COURSES = [
  /* ============================================================
     BEGINNER COURSES — $199, 5 modules, 30 lessons (6 per module)
     ============================================================ */
  {
    id: "ai-foundations",
    title: "AI Foundations: Thinking in Systems",
    tagline: "Start here. Build the mental models that everything AI rests on.",
    level: "Beginner",
    audience: "Students",
    durationWeeks: 8,
    modules: 5,
    lessons: 30,
    price: 199,
    originalPrice: 398,
    nextCohort: "Aug 12, 2026",
    featured: true,
    accent: "blue",
    outcomes: [
      "Reason about problems like an AI engineer",
      "Read and critique AI news without hype",
      "Build 3 portfolio-ready mini projects",
      "Understand the full AI stack end-to-end",
    ],
    syllabus: [
      { num: "01", name: "How AI Actually Works", project: "Diagram a real AI system end-to-end", lessons: ["What AI really is (and isn't)", "The AI stack: data, model, inference, UI", "How models learn: training in plain English", "Tokens, embeddings, vectors demystified", "The inference loop: prompt to output", "Why AI fails (and how to spot it)"] },
      { num: "02", name: "Thinking in Systems", project: "Map a real-world problem as an AI system", lessons: ["Systems thinking vs feature thinking", "Inputs, outputs, and feedback loops", "Constraints and trade-offs", "When to use AI vs rules-based code", "Cost and latency budgets", "Reading an AI architecture diagram"] },
      { num: "03", name: "Reading AI News Without Hype", project: "Write a hype-free teardown of an AI launch", lessons: ["The AI hype cycle, explained", "Marketing language vs technical reality", "Reading research papers as a non-researcher", "Spotting benchmark gaming", "Evaluating 'state of the art' claims", "Building your AI BS detector"] },
      { num: "04", name: "Your First AI Projects", project: "Ship 3 mini AI demos to a portfolio", lessons: ["Project 1: a prompt-driven tool", "Project 2: a RAG mini-search", "Project 3: a simple AI agent", "Using AI APIs safely and cheaply", "Version control and portfolio hygiene", "Writing a README that gets attention"] },
      { num: "05", name: "Capstone — Build a Real AI Demo", project: "Ship a polished AI demo with a landing page", lessons: ["Picking a problem worth solving", "Designing the user experience", "Building the AI core", "Wrapping it in a UI", "Deploying live on Vercel", "Demo day: presenting your work"] },
    ],
  },
  {
    id: "web-builder-pro",
    title: "Web Builder Pro",
    tagline: "Build modern AI-powered websites and web apps from scratch.",
    level: "Beginner",
    audience: "Students",
    durationWeeks: 10,
    modules: 5,
    lessons: 30,
    price: 199,
    originalPrice: 398,
    nextCohort: "Aug 19, 2026",
    featured: true,
    accent: "cyan",
    outcomes: [
      "Deploy a live AI-powered web app with a real domain",
      "Master HTML, CSS, Tailwind, JavaScript, React, Next.js",
      "Add user authentication and a database with Supabase",
      "Integrate an AI feature (chatbot, search, or generator)",
    ],
    syllabus: [
      { num: "01", name: "Web Fundamentals", project: "Deploy your first webpage live", lessons: ["How browsers render pages", "HTML structure and semantics", "CSS and Tailwind basics", "Responsive design patterns", "Git and GitHub workflow", "Deploy to Vercel"] },
      { num: "02", name: "JavaScript for Builders", project: "Build an interactive quiz app", lessons: ["Variables, functions, logic", "DOM manipulation", "Fetch API and JSON", "Async and await", "Error handling", "Local storage and state"] },
      { num: "03", name: "React + Next.js", project: "Build a blog with CMS", lessons: ["Components and props", "State and hooks", "React Router and navigation", "Next.js App Router", "Server vs client components", "SEO and meta tags"] },
      { num: "04", name: "Backend with Supabase", project: "Build a full user auth system", lessons: ["Supabase setup and tables", "Auth with email and OAuth", "Row level security", "Realtime subscriptions", "File uploads and storage", "API routes in Next.js"] },
      { num: "05", name: "Capstone — Ship a Live AI Web App", project: "Launch your own AI web product", lessons: ["Integrating Claude or OpenAI API", "Streaming AI responses", "AI chat interface design", "Stripe payments integration", "Custom domain and analytics", "Launch and demo day"] },
    ],
  },
  {
    id: "prompt-engineering",
    title: "Prompt Engineering Mastery",
    tagline: "From vibes-based prompting to engineered, reproducible prompts.",
    level: "Beginner",
    audience: "Professionals",
    durationWeeks: 6,
    modules: 5,
    lessons: 30,
    price: 199,
    originalPrice: 398,
    nextCohort: "Jul 22, 2026",
    featured: true,
    accent: "violet",
    outcomes: [
      "Design prompts that ship to production",
      "Build a reusable prompt library for your team",
      "Evaluate prompts with real metrics",
      "Save 40%+ on API costs through better prompting",
    ],
    syllabus: [
      { num: "01", name: "Foundations of Prompting", project: "Reverse-engineer a real production prompt", lessons: ["How LLMs actually read prompts", "System vs user vs assistant roles", "Tokens, context windows, and limits", "Temperature, top-p, and sampling", "Prompt structure patterns", "Common pitfalls and anti-patterns"] },
      { num: "02", name: "Prompt Patterns & Engineering", project: "Build a library of 10 reusable patterns", lessons: ["Few-shot prompting", "Chain-of-thought reasoning", "Self-critique and refinement", "Structured output (JSON, XML)", "Tool use and function calling", "Multi-turn conversation design"] },
      { num: "03", name: "Building a Prompt Library", project: "Ship a versioned prompt library for a team", lessons: ["Prompt versioning and git", "Templating with variables", "A/B testing prompts", "Prompt composition and chaining", "Documentation standards", "Sharing and collaboration workflows"] },
      { num: "04", name: "Evaluation & Metrics", project: "Build an eval harness for your prompts", lessons: ["Why evals matter (and why most teams skip them)", "Automated vs human evals", "LLM-as-judge patterns", "Regression testing for prompts", "Cost and latency tracking", "Production monitoring"] },
      { num: "05", name: "Capstone — Production Prompt System", project: "Ship a real prompt-driven feature to production", lessons: ["Designing the feature", "Building the prompt chain", "Adding guardrails and safety", "Deploying to production", "Monitoring and iterating", "Case study write-up"] },
    ],
  },
  {
    id: "design-to-product",
    title: "Design to Product",
    tagline: "Go from idea to shipped product — design, prototype, and build with AI.",
    level: "Beginner",
    audience: "Students",
    durationWeeks: 8,
    modules: 5,
    lessons: 30,
    price: 199,
    originalPrice: 398,
    nextCohort: "Sep 09, 2026",
    featured: false,
    accent: "amber",
    outcomes: [
      "Design a full product UI in Figma",
      "Generate UI kits with AI tools (v0, Cursor)",
      "Build a live product with no-code AI tools",
      "Launch publicly and get your first 100 users",
    ],
    syllabus: [
      { num: "01", name: "Product Thinking & Ideation", project: "Validate an idea in one day", lessons: ["Problem-first thinking", "User research basics", "Sketching and wireframing", "Competitor mapping", "Defining an MVP scope", "Pitching your idea"] },
      { num: "02", name: "Design Fundamentals (Figma)", project: "Design your first screen in Figma", lessons: ["Typography and colour", "Spacing and layout", "Component design", "Figma basics and shortcuts", "Design systems 101", "Dark and light modes"] },
      { num: "03", name: "UI Design with AI", project: "Generate a full UI kit with AI", lessons: ["v0 by Vercel for UI", "Cursor for design-to-code", "AI design tools landscape", "Design system generation", "Iterating with AI feedback", "Polishing AI-generated UI"] },
      { num: "04", name: "No-Code Building", project: "Turn your design into a live product", lessons: ["Lovable for full-stack apps", "Framer for marketing sites", "Webflow for CMS", "Connecting to databases", "Adding AI features", "Custom domains and deploy"] },
      { num: "05", name: "Capstone — Design to Live Product", project: "Ship a complete product from idea to users", lessons: ["Full product lifecycle", "AI content and assets", "Product Hunt launch", "Social media launch", "Email list building", "Portfolio case study"] },
    ],
  },
  {
    id: "ai-automation-agency",
    title: "AI Automation Agency",
    tagline: "Build AI automations for real businesses and sell them as a service.",
    level: "Beginner",
    audience: "Professionals",
    durationWeeks: 8,
    modules: 5,
    lessons: 30,
    price: 199,
    originalPrice: 398,
    nextCohort: "Aug 26, 2026",
    featured: false,
    accent: "green",
    outcomes: [
      "Build 5 live business automation systems",
      "Land your first paying automation client",
      "Set up an agency with a retainer model",
      "Use N8N, Make, and Claude API professionally",
    ],
    syllabus: [
      { num: "01", name: "The Automation Business Model", project: "Find your first automation client", lessons: ["What businesses pay to automate", "Pricing automations", "Cold outreach templates", "Discovery call framework", "Proposal writing", "Retainer vs project pricing"] },
      { num: "02", name: "N8N Mastery", project: "Build a lead capture automation", lessons: ["N8N self-hosted setup", "Workflow basics", "Triggers and webhooks", "Error handling", "Credentials and security", "Scaling workflows"] },
      { num: "03", name: "AI-Powered Automations", project: "Build an AI email responder", lessons: ["Claude API in N8N", "AI email classification", "Smart routing", "Response generation", "Human-in-the-loop review", "Cost management"] },
      { num: "04", name: "WhatsApp & Messaging Bots", project: "Build a WhatsApp AI assistant", lessons: ["WhatsApp Business API setup", "Chatbot flow design", "Appointment booking", "Order management", "Handoff to humans", "Analytics and improvement"] },
      { num: "05", name: "Capstone — Launch Your Agency", project: "Launch your agency with 3 clients", lessons: ["Full agency setup", "Service menu design", "Case studies from pilots", "Monthly retainer system", "Client onboarding flow", "Scaling beyond yourself"] },
    ],
  },

  /* ============================================================
     INTERMEDIATE COURSES — $299, 7 modules, 42 lessons (6 per module)
     ============================================================ */
  {
    id: "app-builder-studio",
    title: "App Builder Studio",
    tagline: "Build real iOS and Android apps with AI features using React Native.",
    level: "Intermediate",
    audience: "Students",
    durationWeeks: 12,
    modules: 7,
    lessons: 42,
    price: 299,
    originalPrice: 854,
    nextCohort: "Sep 03, 2026",
    featured: true,
    accent: "blue",
    outcomes: [
      "Ship a production mobile app to App Store and Play Store",
      "Master React Native, Expo, and TypeScript",
      "Add at least one AI-powered feature",
      "Implement push notifications and in-app purchases",
    ],
    syllabus: [
      { num: "01", name: "Mobile Dev Mindset + Expo", project: "Run your first app on your phone", lessons: ["Native vs cross-platform", "Expo setup and Expo Go", "Project structure", "Mobile UX principles", "Running on iOS and Android", "Debugging on device"] },
      { num: "02", name: "React Native Fundamentals", project: "Build a notes app", lessons: ["Core components", "Flexbox for mobile", "Expo Router navigation", "Gestures and touch", "Lists and performance", "Forms and input"] },
      { num: "03", name: "TypeScript + Data/Storage", project: "Build an offline-first app", lessons: ["Types and interfaces", "Type-safe components", "AsyncStorage", "SQLite local database", "Firebase Firestore", "Real-time sync"] },
      { num: "04", name: "Authentication + AI Features", project: "Add login with Google + AI camera analyser", lessons: ["Firebase Auth setup", "Supabase Auth", "OAuth providers", "Protected routes", "Camera API with Expo", "Image to AI analysis"] },
      { num: "05", name: "Push Notifications + Payments", project: "Add notifications and in-app purchases", lessons: ["Expo notifications", "Background tasks", "Deep linking", "Stripe mobile SDK", "Apple Pay and Google Pay", "Subscription management"] },
      { num: "06", name: "App Store Submission", project: "Submit to App Store and Play Store", lessons: ["Build and signing", "App Store Connect", "Google Play Console", "Review guidelines", "App icon and splash", "Store listing optimisation"] },
      { num: "07", name: "Capstone — Ship to Both Stores", project: "Ship your own app to both stores", lessons: ["Full app from idea to stores", "Performance and polish", "Analytics setup", "Marketing page", "Demo video", "Portfolio case study"] },
    ],
  },
  {
    id: "saas-forge",
    title: "SaaS Forge",
    tagline: "Build and launch AI-powered SaaS products that make real money.",
    level: "Intermediate",
    audience: "Professionals",
    durationWeeks: 12,
    modules: 7,
    lessons: 42,
    price: 299,
    originalPrice: 854,
    nextCohort: "Sep 17, 2026",
    featured: true,
    accent: "green",
    outcomes: [
      "Launch a SaaS product with real paying users",
      "Build subscription billing with Stripe",
      "Implement the AI core feature with LangChain",
      "Deploy to production on AWS with CI/CD",
    ],
    syllabus: [
      { num: "01", name: "SaaS Product Thinking", project: "Validate your SaaS idea in 48 hours", lessons: ["Finding problems worth solving", "Competitor research", "MVP scoping", "Landing page before building", "Pricing strategy", "Go-to-market plan"] },
      { num: "02", name: "SaaS Architecture + Auth", project: "Build team workspaces", lessons: ["Monolith vs microservices", "Database design", "Multi-tenancy patterns", "Org-based auth", "Roles and permissions", "Invite system"] },
      { num: "03", name: "The AI Core Feature", project: "Build the AI product engine", lessons: ["AI feature design", "LangChain integration", "Streaming output", "Token and cost management", "Prompt versioning", "Guardrails and safety"] },
      { num: "04", name: "Subscription Billing", project: "Add Stripe subscriptions", lessons: ["Stripe billing portal", "Usage-based billing", "Free trials", "Dunning and failed payments", "Webhooks and reconciliation", "Tax and invoicing"] },
      { num: "05", name: "Admin Dashboard + Emails", project: "Build internal ops dashboard + onboarding flow", lessons: ["User management panel", "Revenue metrics", "Feature flags", "Resend email setup", "Transactional emails", "Drip campaigns"] },
      { num: "06", name: "Deploy, Scale, Market", project: "Deploy to production + launch marketing site", lessons: ["Docker compose", "AWS deployment", "CDN setup", "Database backups", "Landing page conversion", "Product Hunt launch"] },
      { num: "07", name: "Capstone — Launch + First 10 Users", project: "Launch your SaaS and get first 10 paying users", lessons: ["Go-to-market execution", "Cold outreach", "Demo calls", "Investor one-pager", "Iterating from feedback", "Portfolio write-up"] },
    ],
  },
  {
    id: "data-intelligence-studio",
    title: "Data Intelligence Studio",
    tagline: "Turn raw data into AI-powered insights, dashboards, and predictions.",
    level: "Intermediate",
    audience: "Professionals",
    durationWeeks: 10,
    modules: 7,
    lessons: 42,
    price: 299,
    originalPrice: 854,
    nextCohort: "Oct 14, 2026",
    featured: false,
    accent: "violet",
    outcomes: [
      "Build a live AI-powered analytics dashboard",
      "Ship a working prediction system",
      "Create an automated data pipeline",
      "Master Python, Pandas, SQL, and scikit-learn",
    ],
    syllabus: [
      { num: "01", name: "Data Thinking + Python Basics", project: "Analyse a real dataset for insights", lessons: ["What data can tell you", "Types of analysis", "Data sources and collection", "Asking the right questions", "Python basics for data", "Jupyter notebooks"] },
      { num: "02", name: "Pandas + Data Cleaning", project: "Clean a messy real-world dataset", lessons: ["Pandas fundamentals", "DataFrames and Series", "Filtering and aggregation", "Handling missing data", "Data cleaning patterns", "Exploratory analysis"] },
      { num: "03", name: "SQL + Supabase", project: "Build a data warehouse", lessons: ["SQL fundamentals", "Joins and aggregations", "Window functions", "Supabase setup", "Data modelling", "Query optimisation"] },
      { num: "04", name: "Visualisation + Streamlit", project: "Build an interactive dashboard", lessons: ["Plotly charts", "Streamlit dashboards", "Dashboard design", "Storytelling with data", "Real-time updates", "Sharing dashboards"] },
      { num: "05", name: "AI for Data Analysis", project: "Build an AI data analyst", lessons: ["Claude API for data questions", "Natural language to SQL", "Automated insight generation", "AI-powered reporting", "Context injection", "Hallucination prevention"] },
      { num: "06", name: "ML Basics + Prediction Systems", project: "Build a churn prediction model", lessons: ["ML without deep maths", "scikit-learn pipeline", "Train/test split", "Feature engineering", "Model evaluation", "Deploying models with Streamlit"] },
      { num: "07", name: "Capstone — AI Analytics Product", project: "Build and deploy a complete AI analytics product", lessons: ["End-to-end data product", "Real data source integration", "User-facing dashboard", "Automated pipeline", "Documentation", "Portfolio presentation"] },
    ],
  },
  {
    id: "cloud-devops-launchpad",
    title: "Cloud and DevOps Launchpad",
    tagline: "Deploy, scale, and manage modern AI products in the cloud like a pro.",
    level: "Intermediate",
    audience: "Professionals",
    durationWeeks: 8,
    modules: 7,
    lessons: 42,
    price: 299,
    originalPrice: 854,
    nextCohort: "Oct 28, 2026",
    featured: false,
    accent: "amber",
    outcomes: [
      "Build a fully automated CI/CD pipeline",
      "Deploy on a Kubernetes cluster",
      "Provision infrastructure with Terraform",
      "Set up monitoring, alerting, and security",
    ],
    syllabus: [
      { num: "01", name: "Cloud + DevOps Fundamentals", project: "Deploy your first app to AWS", lessons: ["Cloud computing concepts", "AWS core services", "IAM and security basics", "SSH and servers", "Networking fundamentals", "Cost management"] },
      { num: "02", name: "Docker Mastery", project: "Containerise a full-stack app", lessons: ["Dockerfile writing", "Multi-stage builds", "Docker compose", "Container networking", "Volumes and persistence", "Image optimisation"] },
      { num: "03", name: "CI/CD Pipelines", project: "Build an automated deploy pipeline", lessons: ["GitHub Actions workflows", "Automated testing", "Deployment gates", "Environment management", "Secrets handling", "Rollback strategies"] },
      { num: "04", name: "Kubernetes", project: "Deploy on a K8s cluster", lessons: ["Pods and deployments", "Services and ingress", "ConfigMaps and Secrets", "Auto-scaling", "Health checks", "Kustomize and Helm"] },
      { num: "05", name: "Infrastructure as Code", project: "Build entire infra with Terraform", lessons: ["Terraform basics", "AWS with Terraform", "State management", "Modules and reuse", "Variables and outputs", "Workspaces"] },
      { num: "06", name: "Monitoring + Security", project: "Build a monitoring dashboard + audit your deployment", lessons: ["Prometheus metrics", "Grafana dashboards", "Log aggregation", "Alerting setup", "HTTPS and certificates", "Security scanning"] },
      { num: "07", name: "Capstone — Production Deployment", project: "Deploy a complete AI product to production", lessons: ["End-to-end DevOps pipeline", "Blue-green deployment", "Disaster recovery", "Cost optimisation", "Documentation", "On-call readiness"] },
    ],
  },
  {
    id: "game-studio-ai",
    title: "Game Studio AI",
    tagline: "Build real games with AI — web games, mobile games, and AI mechanics.",
    level: "Intermediate",
    audience: "Students",
    durationWeeks: 10,
    modules: 7,
    lessons: 42,
    price: 299,
    originalPrice: 854,
    nextCohort: "Nov 11, 2026",
    featured: false,
    accent: "cyan",
    outcomes: [
      "Ship three playable games to the web",
      "Master Phaser.js and Three.js for game dev",
      "Add AI-powered game mechanics (enemies, dialogue)",
      "Publish on Itch.io and earn revenue",
    ],
    syllabus: [
      { num: "01", name: "Game Design Thinking", project: "Design your first game on paper", lessons: ["Game mechanics and loops", "Player psychology", "Level design basics", "Monetisation models", "Game feel and juice", "Prototyping on paper"] },
      { num: "02", name: "Web Games with Phaser.js", project: "Build a side-scroller game", lessons: ["Phaser setup", "Sprites and animation", "Physics engine", "Collision detection", "Sound effects", "Score and lives system"] },
      { num: "03", name: "JavaScript Game Mechanics", project: "Build a puzzle game", lessons: ["Game state management", "Local leaderboards", "Save and load", "Particle effects", "Tween animations", "Mobile touch controls"] },
      { num: "04", name: "3D with Three.js", project: "Build a 3D browser game", lessons: ["Three.js scenes", "3D models and textures", "Camera controls", "Simple 3D physics", "Lighting and shadows", "Performance optimisation"] },
      { num: "05", name: "AI in Games", project: "Build a game with AI enemies", lessons: ["AI behaviour trees", "Claude for dynamic dialogue", "Procedural generation", "Adaptive difficulty", "AI-generated content", "Balancing AI gameplay"] },
      { num: "06", name: "Mobile + Multiplayer", project: "Port your game to mobile + 2-player mode", lessons: ["Capacitor for mobile", "Touch controls", "Mobile performance", "WebSocket basics", "Firebase realtime sync", "Lobby and matchmaking"] },
      { num: "07", name: "Capstone — Ship Your Game", project: "Build and launch your original game", lessons: ["Original game concept", "Full development cycle", "Marketing trailer with AI", "Itch.io publishing", "Monetisation setup", "Portfolio write-up"] },
    ],
  },
  {
    id: "ai-security-engineer",
    title: "AI Security Engineer",
    tagline: "Build AI-powered security systems, ethical hacking tools, and products.",
    level: "Intermediate",
    audience: "Professionals",
    durationWeeks: 10,
    modules: 7,
    lessons: 42,
    price: 299,
    originalPrice: 854,
    nextCohort: "Nov 25, 2026",
    featured: false,
    accent: "blue",
    outcomes: [
      "Build an AI-powered vulnerability scanner",
      "Conduct a full penetration test",
      "Secure an AWS environment end-to-end",
      "Create a real-time security monitoring dashboard",
    ],
    syllabus: [
      { num: "01", name: "Security Mindset + OWASP", project: "Audit your own project for vulnerabilities", lessons: ["Attacker vs defender thinking", "OWASP Top 10", "Threat modelling", "Security checklists", "Responsible disclosure", "Security culture"] },
      { num: "02", name: "Network Security", project: "Map and analyse a network", lessons: ["TCP/IP and protocols", "Wireshark traffic analysis", "Port scanning with Nmap", "Network defence basics", "Firewalls and IDS", "VPN and zero trust"] },
      { num: "03", name: "Web App Security", project: "Find and fix XSS and SQL injection", lessons: ["Common web vulnerabilities", "Burp Suite basics", "Manual testing techniques", "AI-assisted code review", "Session and auth attacks", "Remediation patterns"] },
      { num: "04", name: "Ethical Hacking & Pentesting", project: "Conduct a full pentest on a test environment", lessons: ["Pentesting methodology", "Kali Linux tools", "Exploitation basics", "Privilege escalation", "Lateral movement", "Report writing"] },
      { num: "05", name: "AI for Security", project: "Build an AI vulnerability scanner", lessons: ["Claude for code analysis", "AI threat detection", "Automated security testing", "AI-generated reports", "Anomaly detection with ML", "Adversarial AI basics"] },
      { num: "06", name: "Cloud Security + Monitoring", project: "Secure an AWS environment + build dashboard", lessons: ["AWS security services", "IAM best practices", "S3 and data security", "CloudTrail monitoring", "Log analysis", "Incident response"] },
      { num: "07", name: "Capstone — Security Product", project: "Build and launch a security tool", lessons: ["Productise your scanner", "Landing page", "Pricing model", "Open-source strategy", "Portfolio and GitHub", "Demo day"] },
    ],
  },

  /* ============================================================
     ADVANCED COURSES — $699, 16 modules, 96 lessons (6 per module)
     ============================================================ */
  {
    id: "agent-architect",
    title: "Agent Architect",
    tagline: "Build autonomous AI agents and multi-agent systems that work on their own.",
    level: "Advanced",
    audience: "Professionals",
    durationWeeks: 16,
    modules: 16,
    lessons: 96,
    price: 699,
    originalPrice: 2330,
    nextCohort: "Oct 14, 2026",
    featured: true,
    accent: "violet",
    outcomes: [
      "Ship three production-ready AI agent systems",
      "Master LangChain, LangGraph, CrewAI, and MCP",
      "Build a multi-agent business automation",
      "Deploy an agent product with real users",
    ],
    syllabus: [
      { num: "01", name: "What Agents Actually Are", project: "Build your first agent in 1 hour", lessons: ["Agent vs chatbot vs API", "Tool use and reasoning", "LLM as the brain", "The ReAct loop", "Agent architectures", "When to use agents"] },
      { num: "02", name: "LangChain for Agents", project: "Build a web research agent", lessons: ["Chains and runnables", "Tool creation", "Memory types", "Structured output", "Streaming responses", "Error handling"] },
      { num: "03", name: "RAG — Giving Agents Knowledge", project: "Build a document Q&A agent", lessons: ["Vector embeddings", "Pinecone setup", "Retrieval pipeline", "Context injection", "RAG evaluation", "Hybrid search"] },
      { num: "04", name: "LangGraph — Stateful Agents", project: "Build a multi-step planning agent", lessons: ["Graph-based workflows", "State management", "Conditional edges", "Human-in-the-loop", "Subgraphs", "Persistence"] },
      { num: "05", name: "Multi-Agent with CrewAI", project: "Build a content research crew", lessons: ["Agent roles and goals", "Task delegation", "Sequential crews", "Parallel crews", "Output chaining", "Crew evaluation"] },
      { num: "06", name: "MCP — Connecting to the World", project: "Connect agent to real APIs", lessons: ["MCP architecture", "Building MCP servers", "Database integration", "External tool access", "MCP client design", "Security considerations"] },
      { num: "07", name: "Agent Memory & Learning", project: "Build an agent that remembers users", lessons: ["Short-term memory", "Long-term vector memory", "User preference learning", "Episodic recall", "Memory compression", "Privacy and consent"] },
      { num: "08", name: "Tool Creation & Function Calling", project: "Build a custom tool library", lessons: ["Tool design patterns", "Function calling APIs", "Schema definition", "Tool composition", "Error handling in tools", "Tool testing"] },
      { num: "09", name: "Planning & Reasoning Patterns", project: "Build a planning agent", lessons: ["Chain-of-thought", "Tree of thought", "Reflection patterns", "Self-critique loops", "Decomposition strategies", "When to plan vs. react"] },
      { num: "10", name: "N8N Automation with AI", project: "Build a business automation workflow", lessons: ["N8N with AI nodes", "Email processing agent", "Report generation", "Scheduled agents", "Webhook triggers", "Human escalation"] },
      { num: "11", name: "Vector DBs Deep Dive", project: "Build a production vector search", lessons: ["Pinecone vs Weaviate vs Qdrant", "Embedding models", "Indexing strategies", "Hybrid search", "Filtering and metadata", "Cost optimisation"] },
      { num: "12", name: "Agent Evaluation & Reliability", project: "Build an eval harness for agents", lessons: ["Why agent evals are hard", "Trajectory evaluation", "Outcome evaluation", "LLM-as-judge for agents", "Regression testing", "Production monitoring"] },
      { num: "13", name: "Deploy & Monitor Agents", project: "Deploy agent as a product", lessons: ["FastAPI agent endpoint", "Docker packaging", "Agent observability", "Cost monitoring", "Rate limiting", "Scaling strategies"] },
      { num: "14", name: "Multi-Agent Orchestration", project: "Build a multi-agent business system", lessons: ["Orchestration patterns", "Agent communication", "Conflict resolution", "Shared state", "Supervisor agents", "Production multi-agent"] },
      { num: "15", name: "Agent Product Design & Pricing", project: "Design your agent product", lessons: ["Domain-specific agent design", "User interface for agents", "Pricing models for agents", "Onboarding flows", "Trust and transparency", "Support and iteration"] },
      { num: "16", name: "Capstone — Ship Your Agent Product", project: "Build and launch a real agent product", lessons: ["Full product from idea to launch", "User testing", "Iterating from feedback", "Marketing an agent product", "Demo presentation", "Portfolio case study"] },
    ],
  },
];

'''

# Replace the COURSES array (from "export const COURSES = [" to the closing "];" before "export const EVENTS")
pattern = re.compile(r'export const COURSES = \[.*?\n\];\n', re.DOTALL)
new_src, n = pattern.subn(NEW_COURSES, src)
assert n == 1, f'Expected 1 COURSES replacement, got {n}'

FILE.write_text(new_src)
print(f'Wrote {len(new_src):,} bytes to {FILE}')
print(f'COURSES replacement count: {n}')
